#!/usr/bin/env bash

reportPath="./docs/filesToCache.json"

echo "[" > $reportPath

filesToCache=$(
  find docs \
  -type f \
  -not -name 'filesToCache.json' \
  -not -name 'style.js*' \
  -not -name 'CNAME'
)

echo "$filesToCache" | \
xargs -I{} echo "{}" | \
sed -e "s/^docs//" | \
xargs -I{} echo '  "{}",' | \
sed -e '$ s/,$//' \
>> $reportPath

echo "]" >> $reportPath
