#!/usr/bin/env bash

reportPath="./docs/filesToCache.json"

echo "[" > $reportPath

changedSinceLastCommit=$(git diff --name-only HEAD -- docs)
newUntrackedFiled=$(git ls-files --others --exclude-standard -- docs)

filesToCache=$({
  printf %s "$changedSinceLastCommit"
  printf "\n"
  printf %s "$newUntrackedFiled"
})

echo "$filesToCache" | \
xargs -I{} echo "{}" | \
sed -e "s/^docs//" | \
xargs -I{} echo '  "{}",' | \
sed -e '$ s/,$//' \
>> $reportPath

echo "]" >> $reportPath
