#!/usr/bin/env bash

nameFilter=(
  grep -v
  -e '/filesToCache\.json$'
  -e '/CNAME$'
  -e '/style\.js.*$'
  -e '/worker\..*$'
)

filterAndFormat () {
  "${nameFilter[@]}" | \
  sed -e "s/^docs//" | \
  awk -v q='"' '{ print "  " q $0 q "," }' | \
  sed -e '$ s/,$//'
}

allFilesPath="./docs/filesToCache.json"
echo "[" > $allFilesPath
find docs -type f | \
filterAndFormat \
>> $allFilesPath
echo "]" >> $allFilesPath

#lastPublish=$(git ls-remote 2>/dev/null | grep refs/heads/main | awk '{print $1}')

changedSinceLastPublish=\
"git diff --name-only --diff-filter=ACMR @{upstream} -- docs"

updatedFilesPath="./docs/updatedFiles.json"
echo "[" > $updatedFilesPath
$changedSinceLastPublish | \
filterAndFormat \
>> $updatedFilesPath
echo "]" >> $updatedFilesPath
